config/routes.rb
Rails.application.routes.draw do
  resources :fan_relationships
  resources :genre_songs
  resources :group_songs
  resources :group_genres
  resources :songs
  resources :genres
  resources :comments
  resources :fan_groups
  resources :groups
  resources :fans

  get "/signin" => "sessions#new", as: "signin"
  get "/fans/:id/follow" => "fans#follow", as: "follow"
  get "/fans/:id/unfollow" => "fans#unfollow", as: "unfollow"

  get "/groups/:id/add_fan" => "groups#add_fan", as: "add"
  get "/groups/:id/remove_fan" => "groups#remove_fan", as: "remove"

  
  post "/login" => "sessions#create"

  post "/logout" => "sessions#destroy", as: "logout"

  root "welcome#home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :group
  belongs_to :fan
end

app/models/fan.rb
class Fan < ApplicationRecord

    has_many :followeds, class_name: "FanRelationship", foreign_key: :follower_id, dependent: :destroy
    # has_many :followed, through: :active_relationships, source: :followed
  
    has_many :followers, class_name: "FanRelationship", foreign_key: :followed_id, dependent: :destroy
    # has_many :followers, through: :passive_relationships, source: :follower

    has_many :fan_groups
    has_many :groups, through: :fan_groups

    has_many :comments

    has_secure_password


    def follow(followed_fan)
        FanRelationship.create(follower_id: self.id, followed_id: followed_fan.id)
    end 

    def unfollow(followed_fan)
        relation= FanRelationship.find_by(follower_id: self.id, followed_id: followed_fan.id)
        relation.destroy
    end

    def already_follows?(show_fan)
        show_fan.followers.find {|follower| follower.follower_id == self.id}
    end

    
end

app/models/fan_group.rb
class FanGroup < ApplicationRecord
  belongs_to :group
  belongs_to :fan
end

app/models/fan_relationship.rb
class FanRelationship < ApplicationRecord
    belongs_to :followed, class_name: "Fan", foreign_key: :followed_id
    belongs_to :folllower, class_name: "Fan", foreign_key: :follower_id
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :group_genres
    has_many :groups, through: :group_genres

    has_many :songs_genre
    has_many :songs, through: :group_songs 

end

app/models/genre_song.rb
class GenreSong < ApplicationRecord
  belongs_to :song
  belongs_to :genre
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :comments
    has_many :commenters, through: "Fan", source: :fans

    has_many :fan_groups
    has_many :fans, through: :fan_groups

    has_many :group_songs
    has_many :songs, through: :group_songs

    has_many :group_genres
    has_many :genres, through: :group_genres

    def add_fan(fan)
        FanGroup.create(fan_id: fan.id, group_id: self.id)
    end 

    def remove_fan(fan)
        relation= FanGroup.find_by(group_id: self.id, fan_id: fan.id)
        relation.destroy
    end

    def has_member?(fan)
        fan.groups.find {|group| group.id == self.id}
    end

    def card_image_url
        if !self.songs.empty?
            self.songs.last.image_url
        else
            url = "https://pbs.twimg.com/profile_images/956698671751446528/J3ZUMcpq_400x400.jpg"
        end
    end

      
end

app/models/group_genre.rb
class GroupGenre < ApplicationRecord
  belongs_to :genre
  belongs_to :group
end

app/models/group_song.rb
class GroupSong < ApplicationRecord
  belongs_to :song
  belongs_to :group
end

app/models/song.rb
class Song < ApplicationRecord
    has_many :group_songs
    has_many :groups, through: :group_songs

    has_many :genre_songs
    has_many :genres, through: :genre_songs
end

app/controllers/fans_controller.rb
class FansController < ApplicationController
    before_action :require_logged_in_fan, only: [:show, :index]

    def index 
        @fans = Fan.all
    end 

    def new
        # render :layout => "welcome"
        @fan = Fan.new
    end
    
    def show
        @fan = get_fan
        @viewing_fan = Fan.find(session[:fan_id])
        @followed = @viewing_fan.already_follows?(@fan)
        @same_viewer = (@fan == @viewing_fan)
    end

    def follow
        @fan = get_fan
        @viewing_fan = Fan.find(session[:fan_id])
        @viewing_fan.follow(@fan)
        redirect_to fan_path(@fan)
    end

    def unfollow 
        @fan = get_fan
        @viewing_fan = Fan.find(session[:fan_id])
        @viewing_fan.unfollow(@fan)
        redirect_to fan_path(@fan)
    end 

    def create
        @fan = Fan.new(fan_params)
        if @fan.save
            session[:fan_id] = @fan.id
            redirect_to fan_path(@fan)
        else 
            redirect_to root_path
        end 
    end

  


    private
    
    def get_fan
        Fan.find(params[:id])
    end

    def fan_params
        params.require(:fan).permit(:name, :location, :profile_image_url, :password, :password_confirmation)
    end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    before_action :require_logged_in_fan, except: [:index, :show]

    def index
        @groups = Group.all
    end

    def new
        @group = Group.new
        @genres = Genre.all
    end

    def show
        @group = get_group
        @viewer = Fan.find(session[:fan_id])
    end

    def create
        @group = Group.create(:name => group_params[:name], :description => group_params[:description])
        genre_ids = group_params[:genre_ids]

        genre_ids.each do |gi|
            gg = @group.group_genres.build(group_id: @group.id, genre_id: gi.to_i)
            gg.save
        end
        @group.add_fan(current_fan)
        redirect_to group_path(@group)

    end

    def add_fan
        @group = get_group
        @fan = Fan.find(session[:fan_id])
        @group.add_fan(@fan)
        redirect_to group_path(@group)
    end

    def remove_fan
        @group = get_group
        @fan = Fan.find(session[:fan_id])
        @group.remove_fan(@fan)
        redirect_to group_path(@group)
    end 

    def edit
    end

    def update
    end

    def destroy
    end

    private

    def get_group
        Group.find(params[:id])
    end

    def group_params
        params.require(:group).permit(:name, :description, :genre_ids => [])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fan_groups_helper.rb
module FanGroupsHelper
end

app/helpers/fans_helper.rb
module FansHelper
end

app/helpers/genre_songs_helper.rb
module GenreSongsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/group_genres_helper.rb
module GroupGenresHelper
end

app/helpers/group_songs_helper.rb
module GroupSongsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
    <div class="form-group">
    <%= f.label "Group Name" %>
    <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: "form-control" %>
    </div>

    <div class="form-group form-check">
    <%= f.label "Genres", class: "form-check-label" %>
    <%= f.collection_check_boxes :genre_ids, @genres, :id, :name, include_hidden: false%>
    </div>

    <%= f.submit class: "btn btn-lg btn-info" %>
<% end %>

app/views/groups/index.html.erb
<div class= "group-page">
    <%= button_to "Create Group", new_group_path, method: :get, class: "group-homepage-btn btn btn-lg btn-info"  %>

    <div class="groups-page-view">
        <div class="row">
        <% @groups.reverse.each do |group| %>

        <div class="card col-lg-4" style="width: 18rem;">
                <img src="<%= group.card_image_url %>" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title"><%= link_to group.name, group_path(group) %></h5>
                    <p class="card-text"><%= group.description %></p>
                </div>
            </div>

        <% end %>
        </div>
    </div>

</div>

app/views/groups/show.html.erb
<div class="group-show-page">
    <div class="group-page-top">
        <h1> Welcome to </h1> <h1 class="group-name"><%= @group.name%></h1> <h1>group! </h1>
        <h5><%= @group.description %></h5>
        <h2>Genres</h2>
        <% @group.genres.each do |genre| %>
            <p> <%= genre.name %> </p>
        <% end %>
    </div>


    <div class= "group-songs">
        <h1>Tracks</h1>
        <div class="row">
        <% @group.songs.each do |song| %>
            <div class="card col-lg-3" style="width: 18rem;">
        <img src="<%=song.image_url %>" class="card-img-top" alt="...">
        <div class="card-body">
            <p class="card-text"> <a href= <%= song.external_link %> > <%= song.title %></a></p>
        </div>
        </div>
        <% end %>
        </div>
    </div>


    <div class="groupie-comment-section" >
    <h3> Comment Section </h3>
        <% @group.comments.each do |comment| %>
            <p> <%= comment.created_at.strftime("%b %e,%l:%M %p") %> : <%=link_to comment.fan.name, fan_path(comment.fan)%> : <%= comment.content %></p>
        <% end %>
    </div>



    
        <% if !@group.has_member?(@current_fan) %>
            <%= button_to("Follow Group", add_path, method: :get, class: "btn btn-info") %>

        <!--Only Logged In Users Can Access Below-->
        <% else %>

            <%= form_for Comment.new, :remote => true do |f| %>


                <div class= "form-group">

                    <p><%= f.text_field :content, class: "form-control"%></p>
                </div>             
                <%= f.hidden_field :fan_id, :value => session[:fan_id] %>
                <%= f.hidden_field :group_id, :value => @group.id%>
                <%= f.submit "Add Comment", class: "btn btn-info" %>
                
            <% end %>
            <div class="create-song">
            <h1 class="add-song-header">Add Song </h1>

                <% if flash[:match_error] %>
                <h2><%= flash[:match_error] %></h2>
                <% end %>
            
            <%= form_for Song.new, :remote => true do |f| %>
                <div class="form-group">
                    <%= f.label :title %>
                    <%= f.text_field :title, class: "form-control"%>
                </div>

                <div class="form-group">
                     <%= f.label :artist %>
                     <%= f.text_field :artist, class: "form-control" %>
                </div>

                <%= f.hidden_field :group_id, :value => @group.id%>

                <%= f.submit class: "btn btn-light btn-lg"%>
                
            <% end%>
            </div>
            <%= button_to("Leave Group", remove_path, method: :get, class: "btn btn-dark") %>
        <% end %>
    </div>
</div>