config/routes.rb
Rails.application.routes.draw do
  resources :fan_relationships
  resources :genre_songs
  resources :group_songs
  resources :group_genres
  resources :songs
  resources :genres
  resources :comments
  resources :fan_groups
  resources :groups
  resources :fans

  get "/signin" => "sessions#new", as: "signin"
  get "/fans/:id/follow" => "fans#follow", as: "follow"
  get "/fans/:id/unfollow" => "fans#unfollow", as: "unfollow"

  get "/groups/:id/add_fan" => "groups#add_fan", as: "add"
  get "/groups/:id/remove_fan" => "groups#remove_fan", as: "remove"

  
  post "/login" => "sessions#create"

  post "/logout" => "sessions#destroy", as: "logout"

  root "welcome#home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :group
  belongs_to :fan
end

app/models/fan.rb
class Fan < ApplicationRecord

    has_many :followeds, class_name: "FanRelationship", foreign_key: :follower_id, dependent: :destroy
    # has_many :followed, through: :active_relationships, source: :followed
  
    has_many :followers, class_name: "FanRelationship", foreign_key: :followed_id, dependent: :destroy
    # has_many :followers, through: :passive_relationships, source: :follower

    has_many :fan_groups
    has_many :groups, through: :fan_groups

    has_many :comments

    has_secure_password


    def follow(followed_fan)
        FanRelationship.create(follower_id: self.id, followed_id: followed_fan.id)
    end 

    def unfollow(followed_fan)
        relation= FanRelationship.find_by(follower_id: self.id, followed_id: followed_fan.id)
        relation.destroy
    end

    def already_follows?(show_fan)
        show_fan.followers.find {|follower| follower.follower_id == self.id}
    end

    
end

app/models/fan_group.rb
class FanGroup < ApplicationRecord
  belongs_to :group
  belongs_to :fan
end

app/models/fan_relationship.rb
class FanRelationship < ApplicationRecord
    belongs_to :followed, class_name: "Fan", foreign_key: :followed_id
    belongs_to :folllower, class_name: "Fan", foreign_key: :follower_id
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :group_genres
    has_many :groups, through: :group_genres

    has_many :songs_genre
    has_many :songs, through: :group_songs 

end

app/models/genre_song.rb
class GenreSong < ApplicationRecord
  belongs_to :song
  belongs_to :genre
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :comments
    has_many :commenters, through: "Fan", source: :fans

    has_many :fan_groups
    has_many :fans, through: :fan_groups

    has_many :group_songs
    has_many :songs, through: :group_songs

    has_many :group_genres
    has_many :genres, through: :group_genres

    def add_fan(fan)
        FanGroup.create(fan_id: fan.id, group_id: self.id)
    end 

    def remove_fan(fan)
        relation= FanGroup.find_by(group_id: self.id, fan_id: fan.id)
        relation.destroy
    end

    def has_member?(fan)
        fan.groups.find {|group| group.id == self.id}
    end

    def card_image_url
        if !self.songs.empty?
            self.songs.last.image_url
        else
            url = "https://pbs.twimg.com/profile_images/956698671751446528/J3ZUMcpq_400x400.jpg"
        end
    end

      
end

app/models/group_genre.rb
class GroupGenre < ApplicationRecord
  belongs_to :genre
  belongs_to :group
end

app/models/group_song.rb
class GroupSong < ApplicationRecord
  belongs_to :song
  belongs_to :group
end

app/models/song.rb
class Song < ApplicationRecord
    has_many :group_songs
    has_many :groups, through: :group_songs

    has_many :genre_songs
    has_many :genres, through: :genre_songs
end

app/controllers/fans_controller.rb
class FansController < ApplicationController
    before_action :require_logged_in_fan, only: [:show, :index]

    def index 
        @fans = Fan.all
    end 

    def new
        # render :layout => "welcome"
        @fan = Fan.new
    end
    
    def show
        @fan = get_fan
        @viewing_fan = Fan.find(session[:fan_id])
        @followed = @viewing_fan.already_follows?(@fan)
        @same_viewer = (@fan == @viewing_fan)
    end

    def follow
        @fan = get_fan
        @viewing_fan = Fan.find(session[:fan_id])
        @viewing_fan.follow(@fan)
        redirect_to fan_path(@fan)
    end

    def unfollow 
        @fan = get_fan
        @viewing_fan = Fan.find(session[:fan_id])
        @viewing_fan.unfollow(@fan)
        redirect_to fan_path(@fan)
    end 

    def create
        @fan = Fan.new(fan_params)
        if @fan.save
            session[:fan_id] = @fan.id
            redirect_to fan_path(@fan)
        else 
            redirect_to root_path
        end 
    end

  


    private
    
    def get_fan
        Fan.find(params[:id])
    end

    def fan_params
        params.require(:fan).permit(:name, :location, :profile_image_url, :password, :password_confirmation)
    end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

    #for testing purposes only
    def index
        @songs = Song.all
    end

    def new 
        @song = Song.new
    end 

    def create
        song_match = RSpotify::Track.search(song_params[:title])
        @song = Song.new(:title => song_match.first.name, :artist => song_match.first.artists.first.name, :image_url => song_match.first.album.images[0]["url"], external_link: song_match.first.external_urls.values[0], song_genre: song_match.first.artists.first.genres.join(', '))

        
        if @song.artist == song_params[:artist]
            @song.save

            @gs = GroupSong.create(:group_id => song_params[:group_id], :song_id => @song.id)
            redirect_to group_path(@gs.group)
        else 
            flash[:match_error] = "Song/Artist match not found did you mean #{@song.title} by #{@song.artist}?"
            redirect_to group_path(song_params[:group_id])
        end 

        

    end

    private
    def song_params
        params.require(:song).permit(:title, :artist, :group_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fan_groups_helper.rb
module FanGroupsHelper
end

app/helpers/fans_helper.rb
module FansHelper
end

app/helpers/genre_songs_helper.rb
module GenreSongsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/group_genres_helper.rb
module GroupGenresHelper
end

app/helpers/group_songs_helper.rb
module GroupSongsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/fans/_form.html.erb
<%= form_for @current_fan, controller: 'fans', action: 'create' do |f| %>
    <div class="form-group">
  <%= f.label "Username" %>
  <%= f.text_field :name, class: "form-control"%>
  </div>

  <div class="form-group">
  <%= f.label :location %>
  <%= f.text_field :location, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= f.label "Profile Photo" %>
  <%= f.text_field :profile_image_url, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
<br>
  <%= f.submit class: "btn btn-warning" %>
<% end %>

app/views/fans/index.html.erb
<ul><% @fans.each do |fan| %>
    <li><%= link_to fan.name, fan_path(fan) %></li>
    <li><%= image_tag fan.profile_image_url %></li>
<% end %>
</ul>

app/views/fans/new.html.erb
<%= render "form" %>

app/views/fans/show.html.erb
<div class= "profile-info">
    <%= image_tag @fan.profile_image_url, class: "user-img" %>
    
    <div class="profile-text">
        <h5> Groupie </h5>
        <h2><%= "#{@fan.name}'s Profile" %></h2>
        <h4> <%= "location: #{@fan.location}" %></h4>
        <% if @same_viewer%>
        <% elsif @followed %>
            <%= button_to("Unfollow", unfollow_path(@fan), method: :get, class: "btn btn-info") %>
        <% else %>
            <%= button_to("Follow", follow_path(@fan), method: :get, class: "btn btn-info") %>
        <% end %>
        <p><%= pluralize(@fan.followers.count, "follower") %></p>
    </div>
</div>

 

<div class="profile-groups">
    <h4>User's Groups:</h4>
    <div class="row">
    <% @fan.groups.each do |group| %>

       <div class="card col-lg-4" style="width: 18rem;">
            <img src="<%= group.card_image_url %>" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title"><%= link_to group.name, group_path(group) %></h5>
                <p class="card-text"><%= group.description %></p>
            </div>
        </div>

    <% end %>
    </div>
</div>

app/views/songs/_form.html.erb
<h1>Add Song Form</h1>

    <% if flash[:match_error] %>
    <h2><%= flash[:match_error] %></h2>
    <% end %>
 
  
<%= form_for @song do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :artist %>
    <%= f.text_field :artist %>

    <%= f.submit %>
    
<% end%>

app/views/songs/index.html.erb
<h3>Song Index Page</h3>

<ul><% @songs.each do |song| %>
    <li>Song title:<a href= <%song.external_link %> > <%= song.title %></a></li>
    <li><%= image_tag song.image_url %></li> 
<% end %>
</ul>