config/routes.rb
Rails.application.routes.draw do
  resources :fan_relationships
  resources :genre_songs
  resources :group_songs
  resources :group_genres
  resources :songs
  resources :genres
  resources :comments
  resources :fan_groups
  resources :groups
  resources :fans

  get "/signin" => "sessions#new", as: "signin"
  get "/fans/:id/follow" => "fans#follow", as: "follow"
  get "/fans/:id/unfollow" => "fans#unfollow", as: "unfollow"

  get "/groups/:id/add_fan" => "groups#add_fan", as: "add"
  get "/groups/:id/remove_fan" => "groups#remove_fan", as: "remove"

  
  post "/login" => "sessions#create"

  post "/logout" => "sessions#destroy", as: "logout"

  root "welcome#home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :group
  belongs_to :fan
end

app/models/fan.rb
class Fan < ApplicationRecord

    has_many :followeds, class_name: "FanRelationship", foreign_key: :follower_id, dependent: :destroy
    # has_many :followed, through: :active_relationships, source: :followed
  
    has_many :followers, class_name: "FanRelationship", foreign_key: :followed_id, dependent: :destroy
    # has_many :followers, through: :passive_relationships, source: :follower

    has_many :fan_groups
    has_many :groups, through: :fan_groups

    has_many :comments

    has_secure_password


    def follow(followed_fan)
        FanRelationship.create(follower_id: self.id, followed_id: followed_fan.id)
    end 

    def unfollow(followed_fan)
        relation= FanRelationship.find_by(follower_id: self.id, followed_id: followed_fan.id)
        relation.destroy
    end

    def already_follows?(show_fan)
        show_fan.followers.find {|follower| follower.follower_id == self.id}
    end

    
end

app/models/fan_group.rb
class FanGroup < ApplicationRecord
  belongs_to :group
  belongs_to :fan
end

app/models/fan_relationship.rb
class FanRelationship < ApplicationRecord
    belongs_to :followed, class_name: "Fan", foreign_key: :followed_id
    belongs_to :folllower, class_name: "Fan", foreign_key: :follower_id
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :group_genres
    has_many :groups, through: :group_genres

    has_many :songs_genre
    has_many :songs, through: :group_songs 

end

app/models/genre_song.rb
class GenreSong < ApplicationRecord
  belongs_to :song
  belongs_to :genre
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :comments
    has_many :commenters, through: "Fan", source: :fans

    has_many :fan_groups
    has_many :fans, through: :fan_groups

    has_many :group_songs
    has_many :songs, through: :group_songs

    has_many :group_genres
    has_many :genres, through: :group_genres

    def add_fan(fan)
        FanGroup.create(fan_id: fan.id, group_id: self.id)
    end 

    def remove_fan(fan)
        relation= FanGroup.find_by(group_id: self.id, fan_id: fan.id)
        relation.destroy
    end

    def has_member?(fan)
        fan.groups.find {|group| group.id == self.id}
    end

    def card_image_url
        if !self.songs.empty?
            self.songs.last.image_url
        else
            url = "https://pbs.twimg.com/profile_images/956698671751446528/J3ZUMcpq_400x400.jpg"
        end
    end

      
end

app/models/group_genre.rb
class GroupGenre < ApplicationRecord
  belongs_to :genre
  belongs_to :group
end

app/models/group_song.rb
class GroupSong < ApplicationRecord
  belongs_to :song
  belongs_to :group
end

app/models/song.rb
class Song < ApplicationRecord
    has_many :group_songs
    has_many :groups, through: :group_songs

    has_many :genre_songs
    has_many :genres, through: :genre_songs
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fan_groups_helper.rb
module FanGroupsHelper
end

app/helpers/fans_helper.rb
module FansHelper
end

app/helpers/genre_songs_helper.rb
module GenreSongsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/group_songs_helper.rb
module GroupSongsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Groupies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,500;0,900;1,300&display=swap" rel="stylesheet">
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
   
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
 
    </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand">
  <%= image_tag 'groupie_logo.png', class: 'nav-img' %>
  </a>

<% if @current_fan.id != nil %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav ml-auto">
      <a class="nav-link active" href=<%= fan_path(@current_fan) %>>My Profile <span class="sr-only">(current)</span></a>
      <a class="nav-link" href="/groups">Groups </a>
      <%= link_to "Logout", logout_path, method: :post, class: "nav-link"  %>
    </div>
  </div>
<% end %>
</nav>
<br>
    <%= yield %>
  </body>
</html>